
services:

  servidor-web:
    build: .
    container_name:  servidor-web
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: servidor-nginx
    ports:
      - "8081:80"

  mysql:
    image: mysql:8.0
    container_name: servidor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cleaning_company
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
